In [80]:
#Import basic librarys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [81]:
#To Load fiel
df=pd.read_csv("/content/sample_data/creditcard.csv")

In [82]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [83]:
df.shape

(284807, 31)

In [84]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [85]:
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [86]:
#Select input and output from dataset
X=df.drop("Class",axis=1)#input
Y=df["Class"]#output

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
#Train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [89]:
#Use randomoversampling
from imblearn.over_sampling import RandomOverSampler

In [90]:
#RandomOverSampler
#create object of RandomOverSampler() class
ros=RandomOverSampler(random_state=1)

In [91]:
X_train_ros,Y_train_ros=ros.fit_resample(X_train,Y_train)
#fit_resample() inbuild method of RandomOverSampler class

In [92]:
pd.Series(Y_train).value_counts()

0    199007
1       357
Name: Class, dtype: int64

In [93]:
pd.Series(Y_train_ros).value_counts()

0    199007
1    199007
Name: Class, dtype: int64

In [94]:
#Apply randomoversampling on 30% testing data
X_test_ros,Y_test_ros=ros.fit_resample(X_test,Y_test)

In [95]:
pd.Series(Y_test).value_counts()

0    85308
1      135
Name: Class, dtype: int64

In [96]:
pd.Series(Y_test_ros).value_counts()

0    85308
1    85308
Name: Class, dtype: int64

In [97]:
def create_model(model):
  model.fit(X_train_ros,Y_train_ros)
  Y_pred=model.predict(X_test_ros)
  print(classification_report(Y_test_ros,Y_pred))
  print(confusion_matrix(Y_test_ros,Y_pred))

In [98]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

#Applying Logistic Regression

In [99]:
from sklearn.linear_model import LogisticRegression

In [100]:
lr=LogisticRegression()

In [101]:
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.87      0.98      0.92     85308
           1       0.97      0.86      0.91     85308

    accuracy                           0.92    170616
   macro avg       0.92      0.92      0.92    170616
weighted avg       0.92      0.92      0.92    170616

[[83294  2014]
 [11977 73331]]


#Appling Decision Tree

In [102]:
from sklearn.tree import DecisionTreeClassifier
#Create object
dt=DecisionTreeClassifier()

In [103]:
#Calling object
dt=create_model(dt)

              precision    recall  f1-score   support

           0       0.76      1.00      0.86     85308
           1       1.00      0.68      0.81     85308

    accuracy                           0.84    170616
   macro avg       0.88      0.84      0.84    170616
weighted avg       0.88      0.84      0.84    170616

[[85274    34]
 [27341 57967]]


Trying Purning Technique

In [104]:
dt1=DecisionTreeClassifier(max_depth=2,random_state=1)

In [105]:
dt1=create_model(dt1)

              precision    recall  f1-score   support

           0       0.86      0.97      0.91     85308
           1       0.97      0.84      0.90     85308

    accuracy                           0.91    170616
   macro avg       0.91      0.91      0.91    170616
weighted avg       0.91      0.91      0.91    170616

[[83026  2282]
 [13795 71513]]


In [106]:
#Applying 2nd pruning Technique
#min_sample_leaf

In [107]:
dt2=DecisionTreeClassifier(min_samples_leaf=20)

In [108]:
dt2=create_model(dt2)

              precision    recall  f1-score   support

           0       0.83      1.00      0.91     85308
           1       1.00      0.80      0.89     85308

    accuracy                           0.90    170616
   macro avg       0.92      0.90      0.90    170616
weighted avg       0.92      0.90      0.90    170616

[[85225    83]
 [17114 68194]]


Applying Entropy method of DecisionTreeClassifier

In [110]:
dt3=DecisionTreeClassifier(criterion="entropy",min_samples_leaf=20)

In [111]:
dt3=create_model(dt3)

              precision    recall  f1-score   support

           0       0.82      1.00      0.90     85308
           1       1.00      0.79      0.88     85308

    accuracy                           0.89    170616
   macro avg       0.91      0.89      0.89    170616
weighted avg       0.91      0.89      0.89    170616

[[85231    77]
 [18321 66987]]


#Getting Random Forest

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [141]:
#Create object
rfc=RandomForestClassifier(n_estimators=5,max_features=8,random_state=1)

In [142]:
rfc=create_model(rfc)

              precision    recall  f1-score   support

           0       0.79      1.00      0.88     85308
           1       1.00      0.73      0.85     85308

    accuracy                           0.87    170616
   macro avg       0.89      0.87      0.86    170616
weighted avg       0.89      0.87      0.86    170616

[[85299     9]
 [22866 62442]]


#Applying AddaBoost

In [117]:
from sklearn.ensemble import AdaBoostClassifier

In [118]:
#Create object
ada=AdaBoostClassifier(n_estimators=8,random_state=1)

In [119]:
ada=create_model(ada)

              precision    recall  f1-score   support

           0       0.90      0.95      0.92     85308
           1       0.95      0.90      0.92     85308

    accuracy                           0.92    170616
   macro avg       0.92      0.92      0.92    170616
weighted avg       0.92      0.92      0.92    170616

[[80907  4401]
 [ 8816 76492]]


In [ ]:
#Adda Boost Classifier is giving fine score 

#Applying GradientBoosting

In [121]:
from sklearn.ensemble import GradientBoostingClassifier

In [122]:
#Create object
gbc=GradientBoostingClassifier(n_estimators=41,random_state=1)

In [123]:
gbc=create_model(gbc)

              precision    recall  f1-score   support

           0       0.88      0.99      0.93     85308
           1       0.99      0.86      0.92     85308

    accuracy                           0.93    170616
   macro avg       0.93      0.93      0.92    170616
weighted avg       0.93      0.93      0.92    170616

[[84517   791]
 [11974 73334]]


#Applying ExtremGradientBoot

In [125]:
from xgboost import XGBClassifier

In [126]:
xgb=XGBClassifier(n_estimators=10,reg_alpha=1,random_state=1)

In [127]:
#Calling model
xgb=create_model(xgb)

              precision    recall  f1-score   support

           0       0.86      0.99      0.92     85308
           1       0.99      0.84      0.91     85308

    accuracy                           0.92    170616
   macro avg       0.93      0.92      0.92    170616
weighted avg       0.93      0.92      0.92    170616

[[84684   624]
 [13244 72064]]


In [128]:
#All Boosting Alogrithm giving fine score

#Applying Support Vector Machine

In [129]:
from sklearn.svm import LinearSVC

In [130]:
#Create Object
svc=LinearSVC(random_state=1)

In [131]:
svc=create_model(svc)

              precision    recall  f1-score   support

           0       0.82      0.97      0.89     85308
           1       0.97      0.79      0.87     85308

    accuracy                           0.88    170616
   macro avg       0.90      0.88      0.88    170616
weighted avg       0.90      0.88      0.88    170616

[[83058  2250]
 [17794 67514]]


In [132]:
#create object of LinearSVC class
svc1=LinearSVC(random_state=1,C=0.5)
##add some error on training time set error 0.01,0.05,....... 

In [133]:
svc1=create_model(svc1)

              precision    recall  f1-score   support

           0       0.84      0.96      0.90     85308
           1       0.96      0.81      0.88     85308

    accuracy                           0.89    170616
   macro avg       0.90      0.89      0.89    170616
weighted avg       0.90      0.89      0.89    170616

[[82046  3262]
 [15816 69492]]


#Applying KNeighbour algo

In [134]:
#apply KNN algorithm
from sklearn.neighbors import KNeighborsClassifier

In [135]:
#Create object
knc=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)

In [136]:
knc=create_model(knc)

              precision    recall  f1-score   support

           0       0.55      1.00      0.71     85308
           1       0.99      0.18      0.30     85308

    accuracy                           0.59    170616
   macro avg       0.77      0.59      0.50    170616
weighted avg       0.77      0.59      0.50    170616

[[85095   213]
 [70257 15051]]


# Navie Base Therom

In [137]:
#Importing Navie Base Therom

In [138]:
from sklearn.naive_bayes import GaussianNB

In [139]:
#Create object
gnb=GaussianNB()

In [140]:
gnb=create_model(gnb)

              precision    recall  f1-score   support

           0       0.77      0.99      0.86     85308
           1       0.99      0.70      0.82     85308

    accuracy                           0.84    170616
   macro avg       0.88      0.84      0.84    170616
weighted avg       0.88      0.84      0.84    170616

[[84608   700]
 [25914 59394]]


Logistic Regression and Adda Boosting Algos are giving good score 90% 

So these are good for these dataset bold text